### ISSUE TITLE
webpack - browserify + gulp

### ISSUE THREAD

**Issue by italoacasas** [carlosazaustre/universal-js-boilerplate#3]
Hi @carlosazaustre, has pensando en usar webpack en sustitución de browserify y gulp?

**Comment by carlosazaustre** [comment]
Si, de hecho, estoy aprendiendo a utilizarlo. Este proyecto aun le queda por evolucionar :)

**Comment by italoacasas** [comment]
Aceptan PR?

**Comment by carlosazaustre** [comment]
Por supuesto, estaás más que invitado :) tengo que actualizar el Readme
