### ISSUE TITLE
Webpack Dev Server

### ISSUE THREAD

**Issue by kbariotis** [carlosazaustre/universal-js-boilerplate#6]
I've seen the `dev` inside `package.json`'s scripts, but Im not sure what it does? Would you care explaining? 

thx

**Comment by carlosazaustre** [comment]
Hi @kbariotis 

`devDependencies` property in `package.json` is for split dependencies for development and for production.

For example: `react` is a dependence for the final application (production) and `gulp` is a dependence for development stage.

It's only for maintaining a order and best practices :)

**Comment by kbariotis** [comment]
@carlosazaustre I meant the dev script, `npm run dev`.

**Comment by carlosazaustre** [comment]
Oh sorry, it launch a development web server (with webpack )to take advantage of Hot Loader module.
It's only use when your changes CSS, layout, etc..

To develop the complete isomorphic application, may use `npm start`.

**Comment by kbariotis** [comment]
:+1: Thank you
