### ISSUE TITLE
Propose flux for the frontend part

### ISSUE THREAD

**Issue by davesnx** [carlosazaustre/universal-js-boilerplate#8]
Hi again @carlosazaustre,

I want to propose a Flux implementation. 

For me it's the evolution of the DDD on the front-end site. Also, the MVP don't scale really well: when you have some dependencies on the views you should create a few complexity on the view and it's impossible to tests properly.

With Flux you have the abstraction of the EventDomain in the flow of the front-end.

In case that you want to add a small piece of structure on the boilerplate, can be for sure Flux.

What do you thing? Isn't necessary for this repo, because it's a boilerplate? (Like If I propose sequelize or mongoose for the ORM, etc...)

Thanks for reading.

**Comment by sergiodxa** [comment]
+1 to implement Flux, but what implementation? [Reflux](https://github.com/reflux/refluxjs)? [Redux](http://rackt.github.io/redux/)? [Fluxxor](http://fluxxor.com/)? [Flumox](acdlite.github.io/flummox)? A custom implementation using the Facebook Flux Dispatcher? some other?

**Comment by davesnx** [comment]
Flux and Reflux are the only two that I used to implement... 

I listen something about Fluxxor and never about Flummox (it goal is not use singletons, and Promises for all messages). 

Actually my idea was create something  that can help to manage the App Layer and be able to test easily.

Also, we can discuss the test technology.

Thanks for the fast response @sergiodxa

**Comment by carlosazaustre** [comment]
Hi @davesnx and @sergiodxa. It is a pleasure to have you here :)

I would like to implement Flux architecture in this boilerplate project. I still not have played with the architecture, so I encouraged you to "pull-requesting" your commits in order all us learn :)

**Comment by kbariotis** [comment]
@davesnx Just wondering why you're suggesting a Flux implementation only for the client side. Since this is a Universal a.k.a. Isomorphic project, shouldn't be the same structure for both Server/Client sides?

**Comment by davesnx** [comment]
@kbariotis The Flux/Redux architecture is based on requests the actions to the server side. Actually, there are no API or endpoints on this repo, just only a `/*/`route. But mainly, the architecture of Flux/Redux are only based on the client side.
